name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    permissions: # write-all # need to add permissions to either workflow level or job level
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: "Dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"
  comment-with-api:
    permissions:
      issues: write
    runs-on: ubuntu-latest # GitHub CLI already included in GitHub-hosted runners
    steps:
      - name: "Create comment with API"
        run:
          | # SINGLE LINE: gh api -X POST https://api.github.com/repos/${OWNER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments -f body='Comment but from the API call not the action'
          gh api -X POST \
          https://api.github.com/repos/${OWNER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='
          Comment but from the API call not the action
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN set of permissions on this repo only, valid only for the duration of this run of the workflow
          OWNER: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
